language: node_js
node_js:
  - '4'
  - '6'
before_install:
  - npm install -g npm@latest-2
before_deploy:
  - 'git config --global user.email "smassa@groupon.com"'
  - 'git config --global user.name "Sean Massa"'
deploy:
  provider: script
  script: ./node_modules/.bin/nlm release
  skip_cleanup: true
  'on':
    branch: master
    node: '4'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
